### ISSUE TITLE
Not builds on linux and windows

### ISSUE THREAD

**Issue by ydrews** [jonbrennecke/edflib#1]
that's what i have whet try node-gyp build

gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.9.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/andrey/Work/test-libs/node_modules/edflib/src/node/build'
  CXX(target) Release/obj.target/edflib/edfjs.o
In file included from ../edfjs.cpp:11:0:
../edfjs.h:14:43: error: expected class-name before ‘,’ token
 class EdfWrapper : public node::ObjectWrap, public Edf
                                           ^
../edfjs.h:19:33: error: ‘Arguments’ does not name a type
  static Handle<Value> New(const Arguments& args);
                                 ^
../edfjs.h:19:44: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static Handle<Value> New(const Arguments& args);
                                            ^
../edfjs.h:21:37: error: ‘Arguments’ does not name a type
  static Handle<Value> GetData(const Arguments& args);
                                     ^
../edfjs.h:21:48: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static Handle<Value> GetData(const Arguments& args);
                                                ^
../edfjs.h:22:39: error: ‘Arguments’ does not name a type
  static Handle<Value> GetHeader(const Arguments& args);
                                       ^
../edfjs.h:22:50: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static Handle<Value> GetHeader(const Arguments& args);
                                                  ^
../edfjs.cpp:23:37: error: ‘Arguments’ does not name a type
 Handle<Value> EdfWrapper::New(const Arguments& args)
                                     ^
../edfjs.cpp:23:48: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> EdfWrapper::New(const Arguments& args)
                                                ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h: In static member function ‘static v8::Handle<v8::Value> EdfWrapper::New(const int&)’:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../edfjs.cpp:26:14: error: within this context
  HandleScope scope;
              ^
../edfjs.cpp:29:11: error: request for member ‘IsConstructCall’ in ‘args’, which is of non-class type ‘const int’
  if (args.IsConstructCall()) {
           ^
../edfjs.cpp:30:36: error: invalid types ‘const int[int]’ for array subscript
   String::Utf8Value filename(args[0]->IsUndefined() ? String::New("") : args[0]->ToString());
                                    ^
../edfjs.cpp:30:55: error: ‘New’ is not a member of ‘v8::String’
   String::Utf8Value filename(args[0]->IsUndefined() ? String::New("") : args[0]->ToString());
                                                       ^
../edfjs.cpp:30:79: error: invalid types ‘const int[int]’ for array subscript
   String::Utf8Value filename(args[0]->IsUndefined() ? String::New("") : args[0]->ToString());
                                                                               ^
../edfjs.cpp:32:8: error: ‘class EdfWrapper’ has no member named ‘Wrap’
   obj->Wrap(args.This());
        ^
../edfjs.cpp:32:18: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
   obj->Wrap(args.This());
                  ^
../edfjs.cpp:33:15: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
   return args.This();
               ^
../edfjs.cpp:38:37: error: invalid types ‘const int[int]’ for array subscript
   Local<Value> argv[argc] = { args[0] };
                                     ^
../edfjs.cpp:39:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(EdfWrapper::constructor->NewInstance(argc, argv));
                ^
../edfjs.cpp:39:45: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Function>’
   return scope.Close(EdfWrapper::constructor->NewInstance(argc, argv));
                                             ^
../edfjs.cpp: At global scope:
../edfjs.cpp:48:41: error: ‘Arguments’ does not name a type
 Handle<Value> EdfWrapper::GetData(const Arguments& args)
                                         ^
../edfjs.cpp:48:52: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> EdfWrapper::GetData(const Arguments& args)
                                                    ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h: In static member function ‘static v8::Handle<v8::Value> EdfWrapper::GetData(const int&)’:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../edfjs.cpp:51:14: error: within this context
  HandleScope scope;
              ^
../edfjs.cpp:52:27: error: ‘node::ObjectWrap’ has not been declared
  EdfWrapper *self = node::ObjectWrap::Unwrap<EdfWrapper>(args.This());
                           ^
../edfjs.cpp:52:56: error: expected primary-expression before ‘>’ token
  EdfWrapper *self = node::ObjectWrap::Unwrap<EdfWrapper>(args.This());
                                                        ^
../edfjs.cpp:52:63: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
  EdfWrapper *self = node::ObjectWrap::Unwrap<EdfWrapper>(args.This());
                                                               ^
../edfjs.cpp:55:31: error: invalid types ‘const int[int]’ for array subscript
  size_t index = (size_t)args[0]->IsUndefined() ? 0 : args[0]->NumberValue();
                               ^
../edfjs.cpp:55:60: error: invalid types ‘const int[int]’ for array subscript
  size_t index = (size_t)args[0]->IsUndefined() ? 0 : args[0]->NumberValue();
                                                            ^
../edfjs.cpp:62:42: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> array = Array::New(samples);
                                          ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:65:37: error: no matching function for call to ‘v8::Number::New(double&)’
   array->Set( i, Number::New(data[i]) );
                                     ^
../edfjs.cpp:65:37: note: candidate is:
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2483:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2483:24: note:   candidate expects 2 arguments, 1 provided
../edfjs.cpp:67:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close(array);
               ^
../edfjs.cpp: At global scope:
../edfjs.cpp:76:43: error: ‘Arguments’ does not name a type
 Handle<Value> EdfWrapper::GetHeader(const Arguments& args)
                                           ^
../edfjs.cpp:76:54: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> EdfWrapper::GetHeader(const Arguments& args)
                                                      ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h: In static member function ‘static v8::Handle<v8::Value> EdfWrapper::GetHeader(const int&)’:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../edfjs.cpp:79:14: error: within this context
  HandleScope scope;
              ^
../edfjs.cpp:80:27: error: ‘node::ObjectWrap’ has not been declared
  EdfWrapper *self = node::ObjectWrap::Unwrap<EdfWrapper>(args.This());
                           ^
../edfjs.cpp:80:56: error: expected primary-expression before ‘>’ token
  EdfWrapper *self = node::ObjectWrap::Unwrap<EdfWrapper>(args.This());
                                                        ^
../edfjs.cpp:80:63: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
  EdfWrapper *self = node::ObjectWrap::Unwrap<EdfWrapper>(args.This());
                                                               ^
../edfjs.cpp:82:38: error: no matching function for call to ‘v8::Object::New()’
  Handle<Object> header = Object::New();
                                      ^
../edfjs.cpp:82:38: note: candidate is:
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2930:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2930:24: note:   candidate expects 1 argument, 0 provided
../edfjs.cpp:85:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("version"), String::New(self->basicHeader_.version));
               ^
../edfjs.cpp:85:39: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("version"), String::New(self->basicHeader_.version));
                                       ^
../edfjs.cpp:86:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("patientId"), String::New(self->basicHeader_.patientId));
               ^
../edfjs.cpp:86:41: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("patientId"), String::New(self->basicHeader_.patientId));
                                         ^
../edfjs.cpp:87:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("recordId"), String::New(self->basicHeader_.recordId));
               ^
../edfjs.cpp:87:40: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("recordId"), String::New(self->basicHeader_.recordId));
                                        ^
../edfjs.cpp:88:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("startdate"), String::New(self->basicHeader_.startdate));
               ^
../edfjs.cpp:88:41: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("startdate"), String::New(self->basicHeader_.startdate));
                                         ^
../edfjs.cpp:89:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("starttime"), String::New(self->basicHeader_.starttime));
               ^
../edfjs.cpp:89:41: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("starttime"), String::New(self->basicHeader_.starttime));
                                         ^
../edfjs.cpp:90:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("bytes"), String::New(self->basicHeader_.bytes));
               ^
../edfjs.cpp:90:37: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("bytes"), String::New(self->basicHeader_.bytes));
                                     ^
../edfjs.cpp:91:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("reserved"), String::New(self->basicHeader_.reserved));
               ^
../edfjs.cpp:91:40: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("reserved"), String::New(self->basicHeader_.reserved));
                                        ^
../edfjs.cpp:92:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("nr"), String::New(self->basicHeader_.nr));
               ^
../edfjs.cpp:92:34: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("nr"), String::New(self->basicHeader_.nr));
                                  ^
../edfjs.cpp:93:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("duration"), String::New(self->basicHeader_.duration));
               ^
../edfjs.cpp:93:40: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("duration"), String::New(self->basicHeader_.duration));
                                        ^
../edfjs.cpp:94:15: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("ns"), String::New(self->basicHeader_.ns));
               ^
../edfjs.cpp:94:34: error: ‘New’ is not a member of ‘v8::String’
  header->Set( String::New("ns"), String::New(self->basicHeader_.ns));
                                  ^
../edfjs.cpp:99:38: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> labels = Array::New(ns);
                                      ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:100:42: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> transducer = Array::New(ns);
                                          ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:101:41: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> dimension = Array::New(ns);
                                         ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:102:39: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> physMin = Array::New(ns);
                                       ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:103:39: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> physMax = Array::New(ns);
                                       ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:104:38: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> digMin = Array::New(ns);
                                      ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:105:38: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> digMax = Array::New(ns);
                                      ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:106:44: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> prefiltering = Array::New(ns);
                                            ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:107:39: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> samples = Array::New(ns);
                                       ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:108:40: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
  Handle<Array> reserved = Array::New(ns);
                                        ^
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:2962:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../edfjs.cpp:112:18: error: ‘New’ is not a member of ‘v8::String’
   labels->Set(i, String::New(self->extendedHeader_[i].labels));
                  ^
../edfjs.cpp:113:22: error: ‘New’ is not a member of ‘v8::String’
   transducer->Set(i, String::New(self->extendedHeader_[i].transducer));
                      ^
../edfjs.cpp:114:21: error: ‘New’ is not a member of ‘v8::String’
   dimension->Set(i, String::New(self->extendedHeader_[i].dimension));
                     ^
../edfjs.cpp:115:19: error: ‘New’ is not a member of ‘v8::String’
   physMin->Set(i, String::New(self->extendedHeader_[i].physMin));
                   ^
../edfjs.cpp:116:19: error: ‘New’ is not a member of ‘v8::String’
   physMax->Set(i, String::New(self->extendedHeader_[i].physMax));
                   ^
../edfjs.cpp:117:18: error: ‘New’ is not a member of ‘v8::String’
   digMin->Set(i, String::New(self->extendedHeader_[i].digMin));
                  ^
../edfjs.cpp:118:18: error: ‘New’ is not a member of ‘v8::String’
   digMax->Set(i, String::New(self->extendedHeader_[i].digMax));
                  ^
../edfjs.cpp:119:24: error: ‘New’ is not a member of ‘v8::String’
   prefiltering->Set(i, String::New(self->extendedHeader_[i].prefiltering));
                        ^
../edfjs.cpp:120:19: error: ‘New’ is not a member of ‘v8::String’
   samples->Set(i, String::New(self->extendedHeader_[i].samples));
                   ^
../edfjs.cpp:121:20: error: ‘New’ is not a member of ‘v8::String’
   reserved->Set(i, String::New(self->extendedHeader_[i].reserved));
                    ^
../edfjs.cpp:125:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("labels"), labels);
              ^
../edfjs.cpp:126:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("transducer"), transducer);
              ^
../edfjs.cpp:127:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("dimension"), dimension);
              ^
../edfjs.cpp:128:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("physMin"), physMin);
              ^
../edfjs.cpp:129:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("physMax"), physMax);
              ^
../edfjs.cpp:130:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("digMin"), digMin);
              ^
../edfjs.cpp:131:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("digMax"), digMax);
              ^
../edfjs.cpp:132:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("prefiltering"), prefiltering);
              ^
../edfjs.cpp:133:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("samples"), samples);
              ^
../edfjs.cpp:134:14: error: ‘New’ is not a member of ‘v8::String’
  header->Set(String::New("reserved"), reserved);
              ^
../edfjs.cpp:136:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close(header);
               ^
../edfjs.cpp: In static member function ‘static void EdfWrapper::Export(v8::Handle<v8::Object>, const char*)’:
../edfjs.cpp:146:69: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
  Local<FunctionTemplate> tpl = FunctionTemplate::New(EdfWrapper::New);
                                                                     ^
../edfjs.cpp:146:69: note: candidate is:
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../edfjs.cpp:147:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
  tpl->SetClassName(String::NewSymbol(name));
                    ^
../edfjs.cpp:151:32: error: ‘NewSymbol’ is not a member of ‘v8::String’
  tpl->PrototypeTemplate()->Set(String::NewSymbol("getData"),
                                ^
../edfjs.cpp:152:44: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   FunctionTemplate::New(EdfWrapper::GetData)->GetFunction());
                                            ^
../edfjs.cpp:152:44: note: candidate is:
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../edfjs.cpp:153:32: error: ‘NewSymbol’ is not a member of ‘v8::String’
  tpl->PrototypeTemplate()->Set(String::NewSymbol("getHeader"),
                                ^
../edfjs.cpp:154:46: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   FunctionTemplate::New(EdfWrapper::GetHeader)->GetFunction());
                                              ^
../edfjs.cpp:154:46: note: candidate is:
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../edfjs.cpp:156:60: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Local<v8::Function>)’
  constructor = Persistent<Function>::New(tpl->GetFunction());
                                                            ^
../edfjs.cpp:156:60: note: candidate is:
In file included from ../edfjs.h:5:0,
                 from ../edfjs.cpp:11:
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:7171:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/andrey/.node-gyp/5.9.0/include/node/v8.h:7171:4: note:   candidate expects 2 arguments, 1 provided
../edfjs.cpp:157:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
  exports->Set(String::NewSymbol(name), constructor);
               ^
../edfjs.cpp: In static member function ‘static v8::Handle<v8::Value> EdfWrapper::New(const int&)’:
../edfjs.cpp:41:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../edfjs.cpp: In static member function ‘static v8::Handle<v8::Value> EdfWrapper::GetData(const int&)’:
../edfjs.cpp:68:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../edfjs.cpp: In static member function ‘static v8::Handle<v8::Value> EdfWrapper::GetHeader(const int&)’:
../edfjs.cpp:137:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/edflib/edfjs.o] Error 1
make: Leaving directory`/home/andrey/Work/test-libs/node_modules/edflib/src/node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/andrey/Work/test-libs/node_modules/edflib/src/node
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by jonbrennecke** [comment]
@ydrews it looks like you're using the wrong node version (the internal node api has changed). This project hasn't been updated in a while so you will have to use node 0.10 to build it.
